
tama: sprites.cpp display.cpp transfer.cpp main.cpp egg.cpp
	g++ display.cpp egg.cpp main.cpp sprites.cpp transfer.cpp -o tama

sprites.o: display_functions.h parent.h

egg.o: egg.h 

display.o: display_functions.h 

transfer.o: display_functions.h parent.h transfer.h

main.o: parent.h display_functions.h transfer.h









